CLASS z01_clase01_06 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z01_clase01_06 IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
    out->write( 'HOLA MUNDO' ).
    out->write( | HOLA MUNDO | ).
  ENDMETHOD.
ENDCLASS.
